dependencies {

    implementation libs.comparator.extensions
    implementation libs.commons.beanutils

    testImplementation libs.commons.lang3
    testImplementation libs.guava
    testImplementation libs.test.object
    testImplementation libs.meanbean
    // Note: use of bundles...
    testImplementation libs.bundles.unit.testing
    testRuntimeOnly libs.junit.platform.launcher
}
